name: GitHub Actions Build

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'workflow_dispatch' }}

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Configure build
      run: ./premake5 vs2022 --with-version=vs2022

    - name: Build
      run: |
        msbuild -m build/GTAIV.EFLC.FusionFix.sln /property:Configuration=Release /property:Platform=Win32

    - name: Download Ultimate ASI Loader x86
      uses: robinraju/release-downloader@v1.11
      with:
        repository: "ThirteenAG/Ultimate-ASI-Loader"
        tag: "Win32-latest"
        fileName: "dinput8-Win32.zip"

    - name: Unpack dependencies
      run: |
          7z x dinput8-Win32.zip -odata/ -y
          del dinput8-Win32.zip
          del data\dinput8-Win32.SHA512

    - name: Pack binaries
      run: |
        ./release.bat

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: GTAIV.EFLC.FusionFix-GFWLMin
        path: release/*

